services:
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/src
    environment:
      - DATABASE_URL=sqlite:///./todo.db
    ports:
      - "8000:8000"