services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.debug
    container_name: frontend_dev
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_BASE_URL=http://backend:8000
    ports:
      - "5173:5173"
    networks:
      - todo_network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.debug
    container_name: backend_dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - "8000:8000"
    networks:
      - todo_network

networks:
  todo_network:
    name: todo_network
    driver: bridge