services:
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_BASE_URL=http://backend:8000
    ports:
      - "5173:5173"
    networks:
      - todo_network
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - ./backend/venv:/app/venv
    environment:
      - DATABASE_URL=sqlite:///./todo.db
    ports:
      - "8000:8000"
    networks:
      - todo_network

networks:
  todo_network:
    name: todo_network
    driver: bridge