services:
  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/app
      - ./backend/venv:/app/venv
    environment:
      - DATABASE_URL=sqlite:///./todo.db
    ports:
      - "8000:8000"